### ISSUE TITLE
having trouble running netsink with cuckoo

### ISSUE THREAD

**Issue by emguru** [shendo/websnort#1]
Don't want to call this an issue because it may not be, but netsink will not redirect after adding the forwarding rules to cuckoo. Is there a way to get it to redirect with the cuckoo forwarding rules in place?

Thanks

**Comment by shendo** [comment]
Hi there.

Am going to assume your issue was with setting up netsink and not websnort?  I have some deployments with websnort integrated in cuckoo too but not all the modules are available on github... yet.  Let me know if I misunderstood.

I generally deploy netsink on its own dedicated VM and connected to the same virtual/hostonly network as the windows guests.

The iptables forwarding rules are on the netsink host, not the cuckoo master. The way the windows guests know to connect to the netsink VM is by setting their default gateway / DNS server as the nestink VM's address.

It _should_ be possible to set netsink up on the cuckoo master directly but you would need to be careful not to interfere with any of the cuckoo operation (agent comms, etc.) so I'd recommend keeping separate.

Let me know if you have specific issues and what hypervisor/environment you have.  A couple of things I have run into before were:
- The OS (eg. RHEL) can have default iptables rules which will need to be purged before allowing netsink to add its redirection.
- The netsink DNS expects to be able to resolve its own address in /etc/hosts else will return loopback or something instead.

I will try to improve some of the documentation for both of these projects soon.
