### ISSUE TITLE
how to edit for ddos alert?

### ISSUE THREAD

**Issue by zufan-yp** [shendo/websnort#4]
ddos alert can't read how to fix?

![image](https://user-images.githubusercontent.com/78656480/110244107-cd849080-7f8f-11eb-8ba0-dd2daa8ed356.png)

**Comment by shendo** [comment]
Hi zufan-yp,

I'm sorry but I don't fully understand your issue.  Are you asking for help with understanding why a signature triggered on your network?  If so and the rules are from the Snort community set, as suggested by the screenshot, you could try the signature or general mailing list detailed at https://www.snort.org/community 

If you just want to edit/remove the rule from being used by websnort, you could look at the rules files imported by the configuration file (usually /etc/snort/snort.conf) and comment out the included rules or change them as you see fit.

I'm not affiliated with Snort/Cisco so can't provide much more assistance on rules but if I misunderstood and it is an issue with websnort output or interface, please let me know and I'll try my best to answer.

Cheers.

**Comment by zufan-yp** [comment]
I uploaded the pcap ddos ​​and couldn't get into the websnort dashboard

**Comment by shendo** [comment]
I think I understand, you have a pcap that snort alerted on DDOS rules and when you run with websnort, you are not seeing the same alerts/hits displayed in the table?

This could either be, snort, when run via websnort, is running with different configuration to what previous raised the alerts/produced your pcap.  Or there is a possibility that websnort has not parsed snort's output correctly when run.

Do you see different alerts if you run snort manually on the command-line, using the same snort conf/settings as configured for websnort?

Sorry if I've misunderstood again.

**Comment by zufan-yp** [comment]
yes, when I uploaded the pcap ddos table it didn't appear as I screenshot it, what's the cause?

**Comment by shendo** [comment]
The alert table will only appear in the results webpage if running snort across the pcap produces any alerts.  Otherwise it will display a message similar to "No alerts generated".  Is this what you are seeing?

If this is the case, i'm guessing snort is not configured with any signatures to flag the traffic you are expecting.
You could confirm by running snort manually on the command-line yourself and checking it's output.

**Comment by zufan-yp** [comment]
Yes, if the port scanning alert with nmap appears in the table, but if the ddos ​​alert does not appear in the table, I use snort manually.

do you have to configure it first on the websnort?

**Comment by shendo** [comment]
Websnort is just running snort underneath based on the config in https://websnort.readthedocs.io/en/latest/installation.html#configuration If you are able to run snort on the command-line yourself and get different results then either the config doesn't match or websnort is not parsing the output correctly.

Are you able to paste the output of running manually against the same pcap, with the alerts you get there?

**Comment by shendo** [comment]
And I guess to be clear, websnort itself does not contain any signatures/rulesets.  It is simply calling snort (or suricata) with whatever rulesets you have configured there.

**Comment by zufan-yp** [comment]
I mean that, if nmap alerts appear in the table above, but ddos ​​alerts do not appear. why is that?

**Comment by shendo** [comment]
Yep, that's what I'm trying to understand.  These ddos alerts you are expecting to see, when you run snort manually (i.e. without using websnort), does snort output the expected ddos alerts along with the nmap ones?  If so it could be a websnort parsing issue of the output, which would be great to get a copy of.

If running snort manually does not produce the hits you are expecting, then it is to do with the signatures/rules being used and not to do with websnort.

Hopefully we're making progress :)

I'm assuming these ddos alerts you are speaking of are from a standard snort signature and not some additional notification/module thing it does that I'm not aware of.  Again, console output from snort would be helpful.

**Comment by zufan-yp** [comment]
if I run snort manually ddos alerts appear on my terminal but, when I upload to websnort the ddos alert does not appear

**Comment by shendo** [comment]
Understood, could you please post (at least a snippet) of the terminal output with these alerts.

**Comment by zufan-yp** [comment]
This rule snort me

#DOS ATTACK DETECTION
alert tcp !$HOME_NET any -> $HOME_NET any (flags: S; msg:"Possible SYN DoS"; flow: stateless; threshold: type both, track by_dst, count 700, seconds 10; sid:10002;rev:1;)
alert tcp !$HOME_NET any -> $HOME_NET any (flags: A; msg:"Possible ACK DoS"; flow: stateless; threshold: type both, track by_dst, count 700, seconds 10; sid:10001;rev:1;)
alert tcp !$HOME_NET any -> $HOME_NET any (flags: R; msg:"Possible RST DoS"; flow: stateless; threshold: type both, track by_dst, count 700, seconds 10; sid:10003;rev:1;)
alert tcp !$HOME_NET any -> $HOME_NET any (flags: F; msg:"Possible FIN DoS"; flow: stateless; threshold: type both, track by_dst, count 700, seconds 10; sid:10004;rev:1;)
alert udp !$HOME_NET any -> $HOME_NET any (msg:"Possible UDP DoS"; flow: stateless; threshold: type both, track by_dst, count 700, seconds 10; sid:10005;rev:1;)
alert icmp !$HOME_NET any -> $HOME_NET any (msg:"Possible ICMP DoS"; threshold: type both, track by_dst, count 700, seconds 10; sid:10006;rev:1;)

#DDOS ATTACK DETECTION
alert tcp !$HOME_NET any -> $HOME_NET any (flags: S; msg:"Possible SYN DDoS"; flow: stateless; threshold: type both, track by_dst, count 100000, seconds 10; sid:100002;rev:1;)
alert tcp !$HOME_NET any -> $HOME_NET any (flags: A; msg:"Possible ACK DDoS"; flow: stateless; threshold: type both, track by_dst, count 100000, seconds 10; sid:100001;rev:1;)
alert tcp !$HOME_NET any -> $HOME_NET any (flags: R; msg:"Possible RST DDoS"; flow: stateless; threshold: type both, track by_dst, count 100000, seconds 10; sid:100003;rev:1;)
alert tcp !$HOME_NET any -> $HOME_NET any (flags: F; msg:"Possible FIN DDoS"; flow: stateless; threshold: type both, track by_dst, count 100000, seconds 10; sid:100004;rev:1;)
alert udp !$HOME_NET any -> $HOME_NET any (msg:"Possible UDP DDoS"; flow: stateless; threshold: type both, track by_dst, count 100000, seconds 10; sid:100005;rev:1;)
alert icmp !$HOME_NET any -> $HOME_NET any (msg:"Possible ICMP DDoS"; threshold: type both, track by_dst, count 100000, seconds 10; sid:100006;rev:1;)

#PING OF DEATH DETECTION
alert icmp any any -> $HOME_NET any (msg:"Possible Ping of Death"; dsize: > 10000; sid:555555;rev:1;)

DDOS with Hping3

![image](https://user-images.githubusercontent.com/78656480/110784089-d4671800-829b-11eb-9f1e-178cfacd6ac7.png)

And

Alert Snort in terminal

![image](https://user-images.githubusercontent.com/78656480/110784130-e2b53400-829b-11eb-998f-6b445a8c5ca6.png)

And 

alerts do not appear in websnort in the table

![image](https://user-images.githubusercontent.com/78656480/110784243-09736a80-829c-11eb-9ce9-24d0a6187e85.png)

**Comment by zufan-yp** [comment]
Do you have any ddos ​​rules suitable for websnort?

**Comment by shendo** [comment]
Thanks for the extra details, that's really helpful.

So I believe the problem here is that the provided rules make use of threshold count/seconds keywords, (which tbh I'm not overly familiar with).

When you are running on a 'live' interface, snort will be seeing all the packets and threshold will be reached and alert generated.  However, my guess is what actually gets logged is the single packet/alert that originally triggered in that time period.  i.e. thresholds seem to be a way not to flood logs with repeating alerts.

Later, in the web ui screenshot it shows a 974 byte snort pcap log being submitted.  That definitely would not contain 700+ packets the rule suggests is needed.

You _could_ try doing a capture using tcpdump during the hping period and submitting that instead `sudo tcpdump -i eth0 -w /tmp/ddos.pcap`.  If it still doesn't show up I'd suspect something with snort's behaviour being different for theshold timing between pcap vs interface (i.e. whether uses packet timestamps or elapsed system time).
Testing snort on command-line with pcap would confirm.  i.e. something like:
` snort -q -y -A console -c /etc/snort/snort.conf -L /tmp/ddos.log -r /tmp/ddos.pcap`

In answer to your last question, no i don't use snort for ddos alerts and couldn't really comment on whether it is a suitable tool for detection.  It looks like the community rules for ddos are geared towards known content strings in the packets, from specific ddos tools, than detecting packet rates.

**Comment by zufan-yp** [comment]
thank you i use

sudo tcpdump -i eth0 -w /tmp/ddos.pcap

can be read on websnort, thanks for the information

![image](https://user-images.githubusercontent.com/78656480/110804289-9fb28b00-82b2-11eb-986e-4e4cee011b3b.png)

**Comment by shendo** [comment]
Excellent, thanks for confirming.  We got there in the end :)
